import express from 'express';
import { ConnectionError, handleHttp } from "../utils/error.handle";


import { deleteUserById, getUsers, getUserById } from '../services/users';

export const getAllUsers = async (req: express.Request, res: express.Response) => {
  try {
    const users = await getUsers();

    return res.status(200).json(users);
  } catch (error) {
    if (error instanceof ConnectionError) {
      setTimeout(() => {

      })
    }
    handleHttp(res, "ERROR_GET_USERS");
    console.log(error);
    return res.sendStatus(400);
  }
};

export const deleteUser = async (req: express.Request, res: express.Response) => {
  try {
    const { id } = req.params;

    const deletedUser = await deleteUserById(id);

    return res.json(deletedUser);
  } catch (error) {
    handleHttp(res, "ERROR_DELETE_USER");
    console.log(error);
    return res.sendStatus(400);
  }
}

export const updateUser = async (req: express.Request, res: express.Response) => {
  try {
    const { id } = req.params;
    const { username } = req.body;

    if (!username) {
      return res.sendStatus(400);
    }

    const user = await getUserById(id);

    user.username = username;
    await user.save();

    return res.status(200).json(user).end();
  } catch (error) {
    handleHttp(res, "ERROR_UPDATE_USER");
    console.log(error);
    return res.sendStatus(400);
  }
}